class MatchAnalyzer:
    def __init__(self):
        self.name = "BetVision AI Analyzer"

    def analyze(self, match_data):
        confidence = 0
        risk = 100

        if match_data.get("home_form", 0) > 70:
            confidence += 20

        if match_data.get("goals_average", 0) > 2:
            confidence += 20

        if match_data.get("defense_strength", 0) > 70:
            confidence += 20

        risk -= confidence

        return {
            "confidence_score": confidence,
            "risk_score": risk,
            "analysis": "Generated by BetVision AI"
        }
